import type { Driver } from '../types'

export function getMockDrivers(): Driver[] {
    return [
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business SUV',
            accountStatus: 'pending',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'deactivated',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'First Class',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            phone: '08123834250',
            email: 'example@example.com',
            vehicleCategory: 'Business',
            accountStatus: 'active',
            idVerification: false,
        },
    ]
}
