import type { Customer } from '../types'

export function getMockCustomers(): Customer[] {
    return [
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'pending',
            idVerification: false,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'deactivated',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
        {
            id: 'Main test',
            dateJoined: '2025-02-19',
            name: 'Timothy Exodus',
            email: 'customer@example.com',
            phone: '08123834250',
            accountStatus: 'active',
            idVerification: true,
        },
    ]
}
